export const source = [
    "Donald Trump",
    "Beale Cipher",
    "Einstein Theory",
    "Python Basics",
    "Mars Rover",
    "Artificial Intelligence",
    "Blockchain Technology",
    "Quantum Computing",
    "Renaissance Art",
    "Silk Road",
    "Climate Change",
    "Electric Cars",
    "Solar Power",
    "Music Theory",
    "Ancient Egypt",
    "Deep Learning",
    "Startup Culture",
    "Mount Everest",
    "Hollywood Cinema",
    "Digital Marketing",
    "Viking History",
    "Robotics Innovation",
];

export const destination = [
    "Machine Learning",
    "Galaxy Formation",
    "Classical Music",
    "Sustainable Farming",
    "Cyber Security",
    "Literary Critique",
    "Space Tourism",
    "Game Development",
    "Mental Health",
    "Public Speaking",
    "Financial Freedom",
    "Quantum Mechanics",
    "Ancient Rome",
    "Virtual Reality",
    "Coral Reefs",
    "Quantum Entanglement",
    "Data Privacy",
    "Nutrition Facts",
    "Clean Energy",
    "Urban Planning",
    "Gravity Hills",
    "Pandora"
];

export const dummyData = {
    nodes: [
      { id: "Tesla, Inc.", group: 1 },
      { id: "McAfee", group: 2 },
      { id: "ILOVEYOU", group: 2 },
      { id: "I Love You", group: 3 },
    ],
    links: [
      { source: "Tesla, Inc.", target: "McAfee" },
      { source: "McAfee", target: "ILOVEYOU" },
      { source: "ILOVEYOU", target: "I Love You" },
    ],
  };