version: '3.8'

services:
  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    networks:
      stima-network:
        aliases:
          - postgresql.stima.local
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/dumps:/dumps
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - 8080:8080 
    volumes:
      - ./be:/app
    depends_on: [postgres]
    environment:
      DATABASE_HOST: postgresql.stima.local
      DATABASE_PORT: 5432 
      GIN_MODE: release
    networks:
      stima-network:
        aliases:
          - api.local  
  frontend:
    build: 
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
      - postgres
    develop:
      watch:
        - path: ./fe/package.json
          action: rebuild
        - path: ./fe/next.config.mjs
          action: rebuild
        - path: ./fe/package-lock.json
          action: rebuild
        - path: ./fe/tailwind.config.ts
          action: rebuild
        - path: ./fe
          target: /app
          action: sync

networks:
  stima-network:

volumes:
  postgres_data: 
